### GET list of accounts
GET http://localhost:8080/account


### GET account by id
GET http://localhost:8080/account/0bb3b04f-3c7c-4872-a69a-8918775b7233


### POST create account
POST http://localhost:8080/account
Content-Type: application/json

{
  "name" : "slyko",
  "type": "BUSINESS"
}
