### Variables
@baseUrl = http://localhost:8090

### GET list of accounts
GET {{baseUrl}}/account


### GET account by id
GET {{baseUrl}}/account/a939d9be-6804-4cca-b7a4-477d15d50a40


### POST create account
POST {{baseUrl}}/account
Content-Type: application/json

{
  "name" : "slyko",
  "type": "BUSINESS"
}

### PUT update account
PUT {{baseUrl}}/account/a939d9be-6804-4cca-b7a4-477d15d50a40
Content-Type: application/json
If-Match: 1

{
  "id": "a939d9be-6804-4cca-b7a4-477d15d50a40",
  "name": "Updated Account",
  "type": "PRIVATE"
}
