### GET list of accounts
GET http://localhost:8080/account


### GET account by id
GET http://localhost:8080/account/a939d9be-6804-4cca-b7a4-477d15d50a40


### POST create account
POST http://localhost:8080/account
Content-Type: application/json

{
  "name" : "slyko",
  "type": "BUSINESS"
}

### PUT update account
PUT http://localhost:8080/account/a939d9be-6804-4cca-b7a4-477d15d50a40
Content-Type: application/json
If-Match: 1

{
  "id": "a939d9be-6804-4cca-b7a4-477d15d50a40",
  "name": "Updated Account",
  "type": "PRIVATE"
}
