### GET list of deals
GET http://localhost:8080/deal


### GET deal by id
GET http://localhost:8080/deal/49d2bb35-da80-4105-a864-65e65b33ac7c


### POST create deal
POST http://localhost:8080/deal
Content-Type: application/json

{
  "name": "First deal",
  "accountId": "6e8449e4-afef-47e1-a5af-9cadeea6c04b",
  "products": [
    {
      "name": "Towar 1",
      "productType": "BUSINESS",
      "cost": 1.20
    }
  ]
}