### GET list of deals
GET http://localhost:8080/deal


### GET deal by id
GET http://localhost:8080/deal/0f370ef8-c1fc-4dab-8ed7-c63c81a4b394


### POST create deal
POST http://localhost:8080/deal
Content-Type: application/json

{
  "name": "First deal",
  "accountId": "b74d7ad3-59c2-45bf-ac44-561d25ee0b5b",
  "products": [
    {
      "name": "Product No. 2",
      "productType": "HOME",
      "cost": 30.10
    }
  ]
}