### GET list of deals
GET http://localhost:8080/deal
    ?relations=true


### GET deal by id
GET http://localhost:8080/deal/d0e214c3-29cc-46c9-9d0c-9973c532abd1
    ?relations=true


### POST create deal
POST http://localhost:8080/deal
Content-Type: application/json

{
  "name": "Initial deal",
  "accountId": "8512544e-1417-41ff-9e60-3315d51c4b5d",
  "products": [
    {
      "name": "Towar Pierwszy",
      "productType": "HOME",
      "cost": 12.20
    }
  ]
}

### PUT update deal
PUT http://localhost:8080/deal/b7e12255-dc83-42b4-a6c2-09d1bf721445
Content-Type: application/json
If-Match: 1

{
  "id": "b7e12255-dc83-42b4-a6c2-09d1bf721445",
  "version": 0,
  "name": "Support deal 3",
  "status": "READY",
  "accountId": "cd05f64c-2c39-49fe-ab33-b83613aeef2e",
  "products": []
}


### PATCH change dealStatus of deal
PATCH http://localhost:8080/deal/0b4abd0b-8a33-48c4-bae3-2b568c63234f/status
Content-Type: application/json
If-Match: 3

{
  "id": "0b4abd0b-8a33-48c4-bae3-2b568c63234f",
  "version": 1,
  "status": "NEW"
}


### DELETE deal by id with all products
DELETE http://localhost:8080/deal/b7e12255-dc83-42b4-a6c2-09d1bf721445
If-Match: 0


### POST add new products to deal
POST http://localhost:8080/deal/d0e214c3-29cc-46c9-9d0c-9973c532abd1/relationships/products
Content-Type: application/json
If-Match: 0

{
  "id": "d0e214c3-29cc-46c9-9d0c-9973c532abd1",
  "version": 0,
  "products": [
    {
      "name": "Additional Towar First",
      "productType": "CAR",
      "cost": 33.20
    },
    {
      "name": "Additional Towar Second",
      "productType": "HOME",
      "cost": 63.20
    }
  ]
}


### POST calculate cost of all products related to Deal
GET http://localhost:8080/deal/d0e214c3-29cc-46c9-9d0c-9973c532abd1/cost


### GET list of Products from Deal by UUID
GET http://localhost:8080/deal/e5aedcf7-018e-4a6f-b2d8-760b22af9df0/relationships/products


### GET list of Deals with specific status
@status =PAID
GET http://localhost:8080/deal/status/{{status}}