### GET list of payments
GET http://localhost:8080/payment


### GET payment by id
GET http://localhost:8080/payment/1


### POST create payment
POST http://localhost:8080/payment
Content-Type: application/json

{
  "paid": "2023-02-03T12:34:56",
  "accountId": "bf8dff14-48fe-4b5c-9195-3a710c262c61"
}


### DELETE remove payment by id
DELETE http://localhost:8080