### GET list of products
GET http://localhost:8080/product


### GET product by id
GET http://localhost:8080/product/61f53c8b-c56d-419d-a37f-812830785fff


### POST create product
POST http://localhost:8080/product
Content-Type: application/json

{
  "name": "Product Example Update",
  "productType": "BUSINESS",
  "cost": 32.39,
  "dealId": "e5aedcf7-018e-4a6f-b2d8-760b22af9df0"
}

// 23c36975-6c30-40de-ad36-d35ea362cf46

### DELETE remove product by id
DELETE http://localhost:8080/product/c5d10ad8-7b4b-401f-aa03-88295bd0b816